import {
  usedForI1,
  usedForI2,
  usedForI3,
  usedForI4,
  usedForI5,
  usedForI6,
  usedForI7,
  usedForI8,
  usedForI9,
  usedForIA,
  usedForIB,
  usedForIC,
  usedForID,
} from "../modules/functionForAll.js";

const arrayDirectionsFirst =
  "UULLULLUULLLURDLDUURRDRRLDURDULLRURDUDULLLUULURURLRDRRRRULDRUULLLLUUDURDULDRRDRUDLRRLDLUDLDDRURURUURRRDDDLLRUDURDULUULLRRULLRULDUDRDRLDLURURUDDUDLURUDUDURLURURRURLUDDRURRDLUURLLRURRDUDLULULUDULDLLRRRDLRDLDUDRDDDRRUURRRRRUURRDRRDLURDRRURDLLUULULLRURDLDDDRRLLRRUURULURUUDDLRRUDDRURUUDLRLRDLRURRRDULLDLRUDDUULRDULURUURDULUDLLRRLDDLRDLRUDRLDDRLRRRDURDULLRRRDRRLUURURDRRDRRLDLUDURURLDUURDRUDRDDRLDRRLDLURURULLUURUDUUDLRLL";
const arrayDirectionsSecond =
  "LLLULLULDDULRLLURLLLRUUDDLRUULRLULLDLLRRDRLRLRLLDRUUURULDRDDLUDLLDUDULLLRLULLLRULDRDRUDLLRLRLLUDULRRRLDRUULDDULLDULULLUDUDLDRDURDLDLLDUDRRRDLUURRUURULLURLDURLRRLLDDUUULDRLUUDUDLURLULUDURRDRLLDDDDDRRULLRLDULULDDRUURRDLUDDDUDURDDRDRULULLLLUURDURUUUULUDLRURRULRDDRURURLLRLUUDUUURDLLDDLUDRLLLUDLLLLULRLURDRRRDUUDLLDLDDDURRDDRURUURDDRURRLDDDURDLLUURUUULRLUURRUDRLLDLURDUDRLULDLRLULULUDDLRDUDRUDLUULUULDURDRRRRLRULLUDRDDRDLDUDRDRRLDLLLLUDDLRULDLLDUULDDRRULRRUURUDRDURLLLDDUUDRUUDLULLD";
const arrayDirectionsThird =
  "UDUUULLDDDDLUDLDULRLRDLULLDDRULDURRLURRUDLRRUDURRDUDRRRUULRLLRLUDLDRRDUURDDRDRDUUUDUDLDLLRRLUURLUUUDDDUURLULURRLURRRDRDURURUDRLRUURUDRUDDDRDRDLDRDURDLDRRDUUDLLURLDDURRRLULDRDRLLRLLLRURLDURDRLDRUURRLDLDRLDDDRLDLRLDURURLLLLDDRDUDLRULULLRDDLLUDRDRRLUUULDRLDURURDUDURLLDRRDUULDUUDLLDDRUUULRRULDDUDRDRLRULUUDUURULLDLLURLRRLDDDLLDRRDDRLDDLURRUDURULUDLLLDUDDLDLDLRUDUDRDUDDLDDLDULURDDUDRRUUURLDUURULLRLULUURLLLLDUUDURUUDUULULDRULRLRDULDLLURDLRUUUDDURLLLLDUDRLUUDUDRRURURRDRDDRULDLRLURDLLRRDRUUUURLDRURDUUDLDURUDDLRDDDDURRLRLUDRRDDURDDRLDDLLRR";
const arrayDirectionsFourth =
  "ULDRUDURUDULLUDUDURLDLLRRULRRULRUDLULLLDRULLDURUULDDURDUUDLRDRUDUDDLDRDLUULRRDLRUULULUUUDUUDDRDRLLULLRRDLRRLUDRLULLUUUUURRDURLLRURRULLLRLURRULRDUURRLDDRRDRLULDDRRDRLULLRDLRRURUDURULRLUDRUDLUDDDUDUDDUDLLRDLLDRURULUDRLRRULRDDDDDRLDLRRLUUDLUURRDURRDLDLDUDRLULLULRLDRDUDLRULLULLRLDDRURLLLRLDDDLLLRURDDDLLUDLDLRLUULLLRULDRRDUDLRRDDULRLLDUURLLLLLDRULDRLLLUURDURRULURLDDLRRUDULUURRLULRDRDDLULULRRURLDLRRRUDURURDURDULURULLRLDD";
const arrayDirectionsFives =
  "DURLRRRDRULDLULUDULUURURRLULUDLURURDDURULLRRUUDLRURLDLRUDULDLLRRULLLLRRLRUULDLDLLRDUDLLRLULRLLUUULULRDLDLRRURLUDDRRLUUDDRRUDDRRURLRRULLDDULLLURRULUDLRRRURRULRLLLRULLRRURDRLURULLDULRLLLULLRLRLLLDRRRRDDDDDDULUUDUDULRURDRUDRLUULURDURLURRDRRRRDRRLLLLUDLRRDURURLLULUDDLRLRLRRUURLLURLDUULLRRDURRULRULURLLLRLUURRULLLURDDDRURDUDDULLRULUUUDDRURUUDUURURRDRURDUDRLLRRULURUDLDURLDLRRRRLLUURRLULDDDUUUURUULDLDRLDUDULRRULDRDULURRUURD";

const directions = {
  Up: "U",
  Left: "L",
  Down: "D",
  Right: "R",
};

let i = '5'

function usedForEnumeration(arr, i) {
  const arr1 = arr.split("");
  arr1.forEach((el) => {
    if (i == "1") {
      return (i = usedForI1(el, i));
    }
    if (i == "2") {
      return (i = usedForI2(el, i));
    }
    if (i == "3") {
      return (i = usedForI3(el, i));
    }
    if (i == "4") {
      return (i = usedForI4(el, i));
    }
    if (i == "5") {
      return (i = usedForI5(el, i));
    }
    if (i == "6") {
      return (i = usedForI6(el, i));
    }
    if (i == "7") {
      return (i = usedForI7(el, i));
    }
    if (i == "8") {
      return (i = usedForI8(el, i));
    }
    if (i == "9") {
      return (i = usedForI9(el, i));
    }
    if (i == "A") {
      return (i = usedForIA(el, i));
    }
    if (i == "B") {
      return (i = usedForIB(el, i));
    }
    if (i == "C") {
      return (i = usedForIC(el, i));
    }
    if (i == "D") {
      return (i = usedForID(el, i));
    }
  });
  return i;
}

console.log(usedForEnumeration(arrayDirectionsFirst, i));
console.log(usedForEnumeration(arrayDirectionsSecond, i));
console.log(usedForEnumeration(arrayDirectionsThird, i));
console.log(usedForEnumeration(arrayDirectionsFourth, i));
console.log(usedForEnumeration(arrayDirectionsFives, i));
